const ACTIONS = {
  FETCH_USER_REQUEST: "MANAGE_USER_REQUEST",
  FETCH_USER_SUCCESS: "MANAGE_USER_SUCCESS",
  FETCH_USER_FAILURE: "MANAGE_USER_FAILURE",
  FETCH_USER_ALL_REQUEST: "FETCH_USERS_ALL_REQUEST",
  FETCH_USER_ALL_SUCCESS: "MANAGE_USER_ALL_SUCCESS",
  FETCH_USER_ALL_FAILURE: "MANAGE_USER_ALL_FAILURE",
};

export default ACTIONS;
